version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202111-02
    steps:
      - checkout
      - run:
          name: "Install packages"
          command: "pip install -U platformio"
      - run:
          name: "Install platformio packages"
          command: "platformio lib -g install 126 794 89"
      - run:
          name: "Copy Config"
          command: "cp include/wifiConfig.tmpl include/wifiConfig.h"
      - run:
          name: "Build"
          command: "platformio run"

workflows:
  build-workflow:
    jobs:
      - build
